export interface Order {
    id: number;
    uuid: string;
    jobId: string;
    jobTypeName: string;
    quantity: number;
    dateOfDelivery: Date;
    bookNumber: number;
    wBookNumber: number;
    printJobStatus: string;
    totalAmount: number;
    discountedAmount: number;
    depositAmount: number;
    pendingAmount: number;
    paymentStatus: string;
    note: string;
    description: string;
    attachmentIds: number[];
    ledgerIds: number[];
    customerId: number;
    customerName: string;
    customerAddress: string;
    customerPrimaryPhone: string;
    customerAlternatePhone: string;
    updatedAt: string;
    createdAt: string;
    createdBy: string;
    createdById: number;
}
