export interface UpdateOrderRequest {
    customerId: number,
    jobType: string,
    quantity: number,
    dateOfDelivery: Date,
    bookNumber: number,
    wBookNumber: number,
    totalAmount: number,
    discountedAmount: number,
    depositAmount: number,
    pendingAmount: number,
    paymentStatus: string,
    note: string,
    description: string,
}
